#!/bin/bash

# Copyright 2018.  Aaron Sprow
# This file is part of pulse_generation.



g++ -I inc/ -std=c++11 -c src/simulation.cpp -o build/simulation.o -lfftw3
g++ -O3 -I inc/ -std=c++11 -c src/wisdomGen.cpp -o wisdomGen.o -lfftw3
#g++ -o wisdomGen wisdomGen.o -lfftw3
g++ -o wisdomGen wisdomGen.o build/simulation.o -lfftw3



